### PR TITLE
Stacys branch

### PR DESCRIPTION
**Pull request by Lofton713**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested? Yes, it worked via postman

checkklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by vickitaylor** [comment]
had an error check line 8, this worked for me.
with sqlite3.connect("./db.sqlite3") as conn:

**Comment by Lofton713** [comment]
line has been updated, and retested - sqlite3.connect("./db.sqlite3")

**Review by vickitaylor — APPROVED** [review]
looks good and worked

**Comment by vickitaylor** [comment]
the get post by user id worked

**Pull request merged**
